### ISSUE TITLE
double tap

### ISSUE THREAD

**Issue by stoffeastrom** [stoffeastrom/touche#11]
How should we handle double tap and cancellation of tap?

The double tap definition should handle this. Add the possibility to delay the tap from the double tap and either trigger double tap or the tap gesture

**Comment by peol** [comment]
Adding this for documentation's sake:

Allow gestures to pause/get explicit access to events, so that it can safely calculate whatever it needs to and then tell the controller that it's safe to trigger other gestures. Example:

tap needs to wait before triggering itself if it could be a doubletap. But shouldn't need to have a dependency on doubletap because of it.

Let doubletap do something like this:
- bind 'tap' gesture
- when 'tap' gesture is triggered, run `controller.pause(this)` where `this` is the doubletap gesture, making the controller queue up all other gestures data/events until told to run again
- when 'doubletap' has done its thing (either noticing that the user _is_ trying to doubletap, or that there's no other tap within the threshold), it will trigger `controller.play(true)` if the other events should be playbacked (e.g. 'doubletap' didn't happen) or `controller.play(false)`/`controller.play()` which means that 'doubletap' happened and the controller should empty the queue for other gestures

**Comment by stoffeastrom** [comment]
Fixed
