### ISSUE TITLE
How should we handle for example win8 with chrome where both mouse/touch events are fired

### ISSUE THREAD

**Issue by stoffeastrom** [stoffeastrom/touche#20]
- Start event should decide the gesture flow
- Gesture should be type dependant. I.e for touch we need to support that you put first 1 finger down and then next.
  This would end up as a 2-finger tap.
- If you use your mouse simultaneously it should be consider as another gesture
- For MSPointer. could we distinguish type? Else it would feel weird to be able to do a 2-finger tap with the mouse and finger.

event.pointerType -> mouse, pen, touch

**Comment by peol** [comment]
I think treating all start events as initiators is the way to go, and we should focus on getting pointer events in since it seems like it's moving into the browser implementations rather fast (webkit, Firefox, IE).

I don't think we need to distinguish the origin of the event, that's what the spec is trying to remove. However, I think we should consider having a radius were gestures would react if events happened inside them. That would allow multiple gestures simultaneously but still support multi-source gestures like 2-finger tap.

**Comment by stoffeastrom** [comment]
So this is how I see on it right now
- Let the start event initiate a new flow. This way we may have several flows for the same element. E.g on chrome/win8 you could do both touch and mouse on the same time independent of each other.
- For pointer events we need to consider having a radius for gestures. So if the next pointer event is inside the previous it belongs to that flow else we consider a new flow. Maybe we should just be able to have one pointer based gesture per element and then this will not be a problem.

We could add a FlowHandler object that the GestureHandler instantiates whenever a new flow is considered. The FlowHandler responsibility would be to handle flow specific things like started, ended, points etc.

**Comment by stoffeastrom** [comment]
https://github.com/stoffeastrom/touche/tree/issue20

I've made an issue20 branch were I've changed the code to let the start event initiate the correct flow. Each flow has it's own "data" scope. This way we have the possibility to have all flows running from the same element. Also added the 'pointer' events flow.

What do you think?

**Comment by stoffeastrom** [comment]
The general idea is implemented. We need to think about how we should handle this when combining touch/mouse but that's another issue.
