### ISSUE TITLE
activate buttons when pressing the space key

### ISSUE THREAD

**Issue by tregusti** [stoffeastrom/touche#23]
If you on desktop tab to a `<button>`, and press the spacekey, I would assume that a tap event would be triggered, but it isn't as of now.

Browsers apply the `:active` pseudo class so it seems logical.

**Comment by peol** [comment]
Isn't that a keypress though? A tap, on desktop a normalized click, is not really the same as activating something. I'd  see it as a keypress + tap if you want the same behavior on both, just as you would when binding a click event (which a space keypress on a button doesn't trigger).

You could always (re-)define the gesture yourself to allow `keydown`/`keyup` to trigger `tapstart`/`tap`, I don't see it as a core functionality to be honest.

**Comment by stoffeastrom** [comment]
Yeah, I am a bit twofold on this one. As peol says,  It could easily be added with a gesture that binds tap and keypress and trigger if appropriate conditions are met.

But still, if you look at the definition for a click on quirksmode

The click event fires when the user clicks on an element OR activates an element by other means (i.e. the keyboard). It is the most important JavaScript event. The other events on this page are strictly subsidiary.

So basically we have four flows that could end up with a "tap"

mousedown, mousemove, mouseup
touchstart, touchmove, touchend
MSPointerDown, MSPointerMove, MSPointerUp
keydown, keyup

I'm pondering this because of the other issue regarding win8 chrome where both touch/mouse are supported. If we are letting the actual start event decide which flow that is active we could opt in for keydown, keyup if it makes sense. 

I'm wondering if there exists other use cases regarding keydown, keyup? As of writing I can't come up with other use cases.
